const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve('app/src/main/assets');
const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch();const errors=[];try{
 const context=await browser.newContext({viewport:{width:360,height:740},hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);
 assert(await page.locator('#splash').isVisible());await page.locator('#splash').waitFor({state:'detached'});assert(await page.locator('#home').isVisible());
 await page.locator('#privacyButton').click();assert(await page.locator('#privacy').isVisible());assert((await page.locator('#privacy').innerText()).includes('m83905976@gmail.com'));await page.locator('#closePrivacy').click();assert(!(await page.locator('#privacy').isVisible()));await page.locator('#privacyButton').click();assert.equal(await page.evaluate(()=>window.handleBack()),true);assert(!(await page.locator('#privacy').isVisible()));
 await page.locator('#about').click();assert(await page.locator('#info').isVisible());await page.locator('#closeInfo').click();assert(!(await page.locator('#info').isVisible()));
 await page.locator('#start').click();assert(await page.locator('#play').isVisible());await page.locator('#pause').click();assert.equal(await page.locator('#pause').innerText(),'Reprendre');let t=await page.evaluate(()=>time);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>time),t);await page.locator('#pause').click();assert.equal(await page.locator('#pause').innerText(),'Pause');
 // Pointer movement and release: both controls must move and then stop.
 for(const [id,direction] of [['left',-1],['right',1]]){const old=await page.evaluate(()=>x);const box=await page.locator('#'+id).boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(130);await page.mouse.up();const now=await page.evaluate(()=>x);assert(direction<0?now<old:now>old);await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>x),now);}
 const field=await page.locator('#field').boundingBox();await page.touchscreen.tap(field.x+field.width*.75,field.y+100);assert(Math.abs(await page.evaluate(()=>x)-300)<3);
 // Deterministic collisions and game-over rather than waiting for random drops.
 await page.evaluate(()=>{items=[{x:x,y:440,bad:false,v:0}];});await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>score),10);
 await page.evaluate(()=>{items=[{x:x,y:440,bad:true,v:0}];});await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>lives),2);
 await page.locator('#quit').click();assert(await page.locator('#home').isVisible());await page.locator('#start').click();await page.evaluate(()=>{score=90;time=0;});await page.waitForTimeout(80);assert(await page.locator('#result').isVisible());assert.equal(await page.locator('#finalScore').innerText(),'90 points');
 await page.locator('#again').click();assert.equal(await page.evaluate(()=>lives),3);assert.equal(await page.evaluate(()=>score),0);await page.evaluate(()=>{lives=1;items=[{x:x,y:440,bad:true,v:0}];});await page.waitForTimeout(80);assert(await page.locator('#result').isVisible());await page.locator('#back').click();assert(await page.locator('#home').isVisible());assert.equal(await page.locator('#record').innerText(),'90');await page.reload();await page.locator('#splash').waitFor({state:'detached'});assert.equal(await page.locator('#record').innerText(),'90');
 await page.locator('#about').click();assert.equal(await page.evaluate(()=>window.handleBack()),true);assert(!(await page.locator('#info').isVisible()));assert.equal(await page.evaluate(()=>window.handleBack()),false);await page.locator('#start').click();assert.equal(await page.evaluate(()=>window.handleBack()),true);assert(await page.locator('#home').isVisible());
 for(const width of [320,360,412,768]){await page.setViewportSize({width,height:740});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.screenshot({path:'ui-home.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: all eleven buttons and privacy policy, touch, movement/release, scoring, lives, timeout, replay, back, record persistence and four screen widths; no JavaScript runtime errors.');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
